languageCode = 'en-US'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[outputs]
home = ['html']
page = ['html']
rss = ['rss']
section = ['html']
taxonomy = ['html']
term = ['html']

[permalinks]
[permalinks.page]
posts = '/:year/:month/:day/'
[permalinks.section]
posts = '/:year/'
