_merge = "deep"
replacements = "github.com/davidsneighbour/hugo-monologue -> ../../hugo-monologue,github.com/davidsneighbour/hugo-modules/modules/head -> ../../hugo-modules/modules/head,github.com/davidsneighbour/hugo-modules/modules/functions -> ../../hugo-modules/modules/functions,github.com/davidsneighbour/hugo-modules/modules/hooks -> ../../hugo-modules/modules/hooks,github.com/davidsneighbour/hugo-modules/modules/debug -> ../../hugo-modules/modules/debug"

[hugoVersion]
extended = false
min = "0.116.0"

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/debug"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/hooks"
disable = false
ignoreConfig = false
ignoreImports = false

################################################################################

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/head"
disable = false
ignoreConfig = false
ignoreImports = false

