baseURL = 'https://kollitsch.me/'
languageCode = 'en-US'
title = 'kollitsch.me'
theme = ['monologue']

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"

[outputs]
home = ['html']
page = ['html']
rss = ['rss']
section = ['html']
taxonomy = ['html']
term = ['html']
